routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


# auth routes
Route::middleware(['auth'])->group(function () {
    Route::get('/', function () {
        return redirect('/vacations');
    })->name('dashboard');

    # vacations list routes
    Route::prefix('vacations')->as('vacations.')->group(function () {
        Route::get('/', [\App\Http\Controllers\VacationController::class, 'index'])->name('index');
        Route::get('/search', [\App\Http\Controllers\VacationController::class, 'search'])->name('search');
        Route::post('/', [\App\Http\Controllers\VacationController::class, 'save'])->name('save');
        Route::post('/{vacation}/apply', [\App\Http\Controllers\VacationController::class, 'apply'])->name('apply');
    });
});

require __DIR__.'/auth.php';

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Role extends Model
{
    use HasFactory;

    const LEAD = 1;
    const EMPLOYEE = 2;


    protected $fillable = ['name'];

    public function users(): BelongsToMany
    {
        return $this->belongsToMany(User::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];


    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles(): BelongsToMany
    {
        return $this->belongsToMany(Role::class);
    }

    public function vacations(): HasMany
    {
        return $this->hasMany(Vacation::class);
    }

    public function hasRole(int $roleId): bool
    {
        return !!$this->roles->firstWhere('id', $roleId);
    }
}

app/Models/Vacation.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Vacation extends Model
{
    use HasFactory;

    protected $fillable = [
        'date_from',
        'date_to'
    ];

    protected $casts = [
        'date_from' => 'date',
        'date_to' => 'date',
        'applied' => 'boolean'
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /*
     * Search user vacations by date return query
     * Add scope in function SearchByDate tщ added query params in function
     */
    public static function scopeSearchByDate(Builder $query, Carbon $dateFrom, Carbon $dateTo): Builder
    {
        return $query
            ->where(function (Builder $query) use ($dateFrom, $dateTo) {
                return $query
                    ->whereDate('date_from', '<=', $dateFrom)
                    ->whereDate('date_to', '>=', $dateFrom);
            })->orWhere(function (Builder $query) use ($dateFrom, $dateTo) {
                return $query
                    ->whereDate('date_from', '>=', $dateFrom)
                    ->whereDate('date_to', '<=', $dateTo);
            })->orWhere(function (Builder $query) use ($dateFrom, $dateTo) {
                return $query
                    ->whereDate('date_from', '>=', $dateFrom)
                    ->whereDate('date_to', '<=', $dateTo);
            });
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/VacationController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Vacation\AppliedRequest;
use App\Http\Requests\Vacation\SearchRequest;
use App\Http\Requests\Vacation\SaveRequest;
use App\Models\Vacation;
use Carbon\Carbon;
use Illuminate\Http\RedirectResponse;

class VacationController extends Controller
{
    private const PER_PAGE = 20;

    /*
     * Return user vacations list
     */
    public function index()
    {
        $vacations = Vacation::with('user')
            ->orderBy('id', 'desc')
            ->paginate(self::PER_PAGE);

        return view('vacation.index', compact('vacations'));
    }
    /*
     * Create user vacation
     * SaveRequest - middleware validation data type
     */
    public function save(SaveRequest $saveRequest): RedirectResponse
    {
        if (auth()->user()->vacations()->firstWhere('applied', true)) {
            return redirect()
                ->back()
                ->with('error_store', 'У вас уже есть запланированная дата');
        }

        auth()->user()->vacations()->create([
            'date_from' => $saveRequest->input('date_from'),
            'date_to' => $saveRequest->input('date_to')
        ]);

        return redirect()
            ->route('vacations.index')
            ->with('success_created', 'Отпуск успешно создан');
    }

    /*
     * Apply user vacation
     * AppliedRequest - middleware validation data type
     */
    public function apply(Vacation $vacation, AppliedRequest $appliedRequest): RedirectResponse
    {
        $vacation->applied = $appliedRequest->input('apply');
        $vacation->save();
        return redirect()->back();
    }

    /*
     * Search user vacations
     * SearchRequest - middleware validation data type
     * Сhecking vacation dates
     * Сheck of vacation confirmation
     */
    public function search(SearchRequest $request)
    {
        $dateFrom = Carbon::parse($request->input('date_from'));
        $dateTo = Carbon::parse($request->input('date_to'));

        if (!!$dateFrom->diff($dateTo)->invert) {
            session()->flash('error_search', 'Дата окончания не может быть меньше даты начала');
            return redirect()->route('vacations.index');
        }

        if (auth()->user()->vacations()->firstWhere('applied', true)) {
            session()->flash('error_search', 'У вас уже есть запланированная дата');
            return redirect()->route('vacations.index');
        }

        $isApplied = !!auth()->user()->vacations()->firstWhere('applied', true);
        $vacations = Vacation::searchByDate($dateFrom, $dateTo)
            ->with('user')
            ->paginate(self::PER_PAGE);

        return view('vacation.index', compact('vacations', 'isApplied'));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="flex-shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link class="text-lg font-semibold" :href="route('dashboard')" :active="request()->routeIs('vacations')">
                        {{ __('Планирование отпусков') }}
                    </x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Выйти') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="flex items-center px-4">
                <div class="flex-shrink-0">
                    <svg class="h-10 w-10 fill-current text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                    </svg>
                </div>

                <div class="ml-3">
                    <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                    <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
                </div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>

resources/views/vacation/index.blade.php
<x-app-layout>
    <x-slot name="header">

    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            @if(session()->exists('error_search'))
            <div class="col-span-12 text-red-800">
                {{ session()->get('error_search') }}
            </div>
            @endif
            <form action="{{ route('vacations.search') }}" method="GET">
                <div class="grid grid-cols-12 gap-10">
                    <div class="col-span-6">
                        <label for="date_from" class="block font-medium text-gray-700">Дата начала</label>
                        <input type="date" name="date_from" id="date_from" value="{{ request()->input('date_from') }}"
                               class="mt-1 focus:ring-blue-400 focus:border-blue-400 block w-full shadow-sm border-gray-300">
                    </div>
                    <div class="col-span-6">
                        <label for="date_to" class="block font-medium text-gray-700">Дата окончания</label>
                        <input type="date" name="date_to" id="date_to" value="{{ request()->input('date_to') }}"
                               class="mt-1 focus:ring-blue-400 focus:border-blue-400 block w-full shadow-sm border-gray-300">
                    </div>


                </div>
                <div class="grid grid-cols-12 gap-20 my-4">
                    <div class="col-span-1 self-end">
                        <button type="submit"
                                class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-semibold rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:none">
                            Найти
                        </button>
                    </div>
                    <div class="col-span-1 self-end">
                        <a href="{{ route('vacations.index') }}"
                           class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-semibold rounded-md text-white bg-gray-400 hover:bg-gray-500 focus:outline-none focus:none">
                            Сбросить
                        </a>
                    </div>
                </div>
            </form>

            @if((isset($isApplied) && !$isApplied) && request()->exists('date_from') && request()->exists('date_to') && auth()->user()->hasRole(\App\Models\Role::EMPLOYEE))
            <form action="{{ route('vacations.save') }}" method="post" class="mt-2">
                @csrf
                <input type="hidden" name="date_from" value="{{ request()->input('date_from') }}">
                <input type="hidden" name="date_to" value="{{ request()->input('date_to') }}">
                <button type="submit"
                        class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-semibold rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:none">
                    Запланировать
                </button>
            </form>
            @endif

            <div class="flex flex-col mt-8">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                        <div class="shadow overflow-hidden border-b border-gray-200">
                            <table class="min-w-full divide-y divide-gray-400">
                                <thead class="bg-gray-200">
                                <tr>
                                    <th scope="col"
                                        class="px-6 py-3 text-left text-sm text-black-500 tracking-wider">
                                        Сотрудник
                                    </th>
                                    <th scope="col"
                                        class="px-6 py-3 text-sm text-left text-black-500 tracking-wider">
                                        Дата начала
                                    </th>
                                    <th scope="col"
                                        class="px-6 py-3 text-left text-sm text-black-500 tracking-wider">
                                        Дата окончания
                                    </th>
                                    <th scope="col"
                                        class="px-6 py-3 text-left text-sm text-black-500 tracking-wider">
                                        Подтвержден
                                    </th>
                                    <th scope="col" class="relative px-6 py-3">

                                    </th>
                                </tr>
                                </thead>
                                <tbody class="bg-white divide-y divide-gray-200">
                                @forelse($vacations as $vacation)
                                <tr>
                                    <td class="px-6 py-4 whitespace-nowrap">
                                        <div class="flex items-center">
                                            <div>
                                                <div class="text-sm font-medium text-gray-900">
                                                    {{ $vacation->user->name }}
                                                </div>
                                                <div class="text-sm text-gray-500">
                                                    {{ $vacation->user->email }}
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap">
                                        <div class="text-sm text-gray-900">
                                            {{ $vacation->date_from->format('Y.m.d') }}
                                        </div>
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap">
                                        <div class="text-sm text-gray-900">
                                            {{ $vacation->date_to->format('Y.m.d') }}
                                        </div>
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                             <span
                                                 class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full {{ $vacation->applied ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800' }}">
                                                    {{ $vacation->applied ? 'Да' : 'Нет' }}
                                                </span>
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                        @if(auth()->user()->hasRole(\App\Models\Role::LEAD))
                                        <form action="{{ route('vacations.apply', $vacation) }}" method="POST">
                                            @csrf
                                            <input type="hidden" name="apply"
                                                   value="{{ $vacation->applied ? 0 : 1 }}">
                                            @if(!$vacation->applied)
                                            <button
                                                type="submit"
                                                class="inline-flex justify-center py-1 px-2 border border-transparent shadow-sm text-sm font-semibold rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:none"
                                            >
                                                Подтвердить
                                            </button>
                                            @endif
                                            @if($vacation->applied)
                                            <button
                                                type="submit"
                                                class="inline-flex justify-center py-1 px-2 border border-transparent shadow-sm text-sm font-semibold rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:none"
                                            >
                                                Отклонить
                                            </button>
                                            @endif
                                        </form>
                                        @endif
                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <td colspan="5" class="text-center py-3">
                                       Запланированные даты отсутствуют
                                    </td>
                                </tr>
                                @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

            {{ $vacations->links() }}
        </div>
    </div>
</x-app-layout>